---

O²_time_use: 1 # secondes
oxygene: 40 # 20 seconds of oxygene because the consumption time of one liter of oxygene is set to one second :)
oxygene_item: "388:0"
oxygene_add: 30

world:
  - "world"
...